### ISSUE TITLE
lines with resistance = 0

### ISSUE THREAD

**Issue by CarlosEpia** [openego/powerd-data#120]
There are 3 transmission lines with r = 0. This sometimes creates problems during the clustering.
![image](https://github.com/openego/powerd-data/assets/62600091/44749eb4-7a86-41e0-b727-7be30a56495a)
The 3 of then are located inside Germany:
![image](https://github.com/openego/powerd-data/assets/62600091/765d6b46-d83f-41ec-bcdb-7b27e715a7d8)

**Comment by ClaraBuettner** [comment]
Needs to be adjusted here: https://github.com/openego/powerd-data/blob/bc0eb256c564397ab4794a7a57fda521527f28c5/src/egon/data/datasets/fix_ehv_subnetworks.py#L123
