### ISSUE TITLE
Demandregio uncompatibility

### ISSUE THREAD

**Issue by CarlosEpia** [openego/powerd-data#124]
The tasks: demandregio.insert-cts-ind-demands, demandregio.insert-society-data and demandregio.insert-household-demand are failing due to incompatibilities with recent versions of Pandas. After removing the upper version constraint, usually Pandas 2.0.3 is installed, and functions like "read_json()" have different behaviours compared to older versions.

@ulfmueller and @ClaraBuettner since we demanregio is an independent repository that has been inactive for about a year, should we create our own fork and adjust it there? Should we provisionally set an upper limit for Pandas?

**Comment by ClaraBuettner** [comment]
We already have and use a fork from demandregio (https://github.com/openego/disaggregator/tree/features/pandas-update). I remember that I did changes there, I can have a look if the right branch is selected.
