### ISSUE TITLE
Create debugging instance on one of our servers

### ISSUE THREAD

**Issue by ulfmueller** [openego/powerd-data#13]
in order to easily create data for the entire system it will be necessary to run the workflow on a server. On my local machine the task: electricity_demand_timeseries.hh_profiles.houseprofiles-in-census-cells is already a bottle-neck in test mode...

**Comment by ClaraBuettner** [comment]
I created an instance for the test mode on our at36 server. Airflow is running on port 8082, the database is on port 59736. 
On airflow port 8081, a database for Germany on port 59763 is created. I just started the pipeline, it might take some days until we can see a result.

@ulfmueller and @CarlosEpia if you need access to the server or have any questions, please let me know.
