### ISSUE TITLE
storage_units and stores cyclic condition is set to false

### ISSUE THREAD

**Issue by ulfmueller** [openego/powerd-data#130]
storage_units and stores should get an cyclic_state_of_charge (e_cyclic resp.) of True! Can we include this in the next version?

**Comment by CarlosEpia** [comment]
Check where is it done in eGo2035 and apply the same for status2019

**Comment by ulfmueller** [comment]
Careful with the stores. In the case of e-mobility the battery stores are cyclic false! But they shouldn't be there anyway because of the dumb charging strategy - I will address this bug asap in #3

**Comment by CarlosEpia** [comment]
Since for 2019 there are not stores, the changes are just applied to storages.
