### ISSUE TITLE
High AC peak loads in Germany

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/powerd-data#139]
Compared to the entsoe-data, our peaks in the AC loads in Germany seem to be too high, it is 108 GW. 
According to the entsoe, the peak load was about 80GW in 2019. 
We should check if we just overestimate the peak load or if also our annual sum is too high.

**Comment by ClaraBuettner** [comment]
@IsGut Could you post the diagram you showed us here?

**Comment by IsGut** [comment]
![DE_month_12](https://github.com/openego/powerd-data/assets/15251685/1136300f-a5a1-4d2a-b81a-cbaf91c4e5d8)
![Total Load DE](https://github.com/openego/powerd-data/assets/15251685/bb57635e-b509-4818-b611-08bd1fa356c7)
![DE_month_1](https://github.com/openego/powerd-data/assets/15251685/9b515405-60f7-4f32-99fe-47aacae20dea)
![DE_month_2](https://github.com/openego/powerd-data/assets/15251685/ed671172-8ea6-477c-99fe-c81ce13c761f)
![DE_month_3](https://github.com/openego/powerd-data/assets/15251685/732bad3a-8492-401c-8f4b-e6563a5ef07a)
![DE_month_4](https://github.com/openego/powerd-data/assets/15251685/b4434101-3cdf-4cc5-9902-15f0b37e557c)
![DE_month_5](https://github.com/openego/powerd-data/assets/15251685/1825ca73-d57c-4730-8d5c-3516f9c00261)
![DE_month_6](https://github.com/openego/powerd-data/assets/15251685/3bef804f-d707-48ba-8386-5d2d193618ce)
![DE_month_7](https://github.com/openego/powerd-data/assets/15251685/caa3d018-1acf-4bef-90ce-277d150f94f5)
![DE_month_8](https://github.com/openego/powerd-data/assets/15251685/f1b28a12-0185-4bf8-80f1-4ba2918b6e9f)
![DE_month_9](https://github.com/openego/powerd-data/assets/15251685/c9fd2a29-66ed-41ac-869a-68c5e07c4986)
![DE_month_10](https://github.com/openego/powerd-data/assets/15251685/4e92dabd-800e-4177-a8b2-10bea29021be)
![DE_month_11](https://github.com/openego/powerd-data/assets/15251685/a28a0553-209f-4b4d-9a2a-99c0304bbcfe)

**Comment by CarlosEpia** [comment]
To start the analysis the total load was divided into the 4 different components it is composed of:
![Demand_by_sector](https://github.com/openego/powerd-data/assets/62600091/aafbd4b1-7268-4c56-9237-450b44cd2d3d)
![Demand_by_sector_areas](https://github.com/openego/powerd-data/assets/62600091/6377168e-8ca2-4078-b479-d06290df1d3d)

**Comment by CarlosEpia** [comment]
The problem with the peak is likely related to the households or CTS demands. The hh demands were disaggregated by type of load profile:
![hh_demand_by_type](https://github.com/openego/powerd-data/assets/62600091/96300746-bcbc-440b-98d0-d10751362315)
![hh_demand_by_type_area](https://github.com/openego/powerd-data/assets/62600091/1e901dde-2a72-4447-b86a-63e0d0a606c0)

**Comment by CarlosEpia** [comment]
In general it look like the profiles make sense. The total sum of the loads matches the annual consumption, but the peaks are too high. The code is working according to the described methodology proposed in https://energyinformatics.springeropen.com/articles/10.1186/s42162-022-00201-y/figures/4. Therefore, it will be necessary to implement something in addition to match also the expected peak loads.

**Comment by CarlosEpia** [comment]
According to [IEE](https://www.iea.org/data-and-statistics/data-tools/real-time-electricity-tracker?tracker=true&from=2019-1-22&to=2019-1-22&category=demand&country=DEU) the load curve for Germany for a working day in January 2019 looks like:
![image](https://github.com/openego/powerd-data/assets/62600091/4e36ae42-02f8-4bbc-9eec-c6f1aa3c9379)
But our load profile looks like this:
![image](https://github.com/openego/powerd-data/assets/62600091/507fb72a-fa91-4678-8c76-36b58e1d6068)

Our smallest demand is 13GW lower than the measured data. Our max peak is around 35 GW higher. Additionally, the temporal allocation of the peaks differs.

**Comment by CarlosEpia** [comment]
The industry demand data is reliable to a certain extent. Therefore I would propose to keep the industry demand, while scaling the sum of CTS and HH to match the measured hourly demand provided by entso-e or IEA. What do you think @ClaraBuettner and @ulfmueller ?

**Comment by CarlosEpia** [comment]
Since Demand Regio is already installed in powerD-data, it is an option to use it for status and future scenarios.

**Comment by CarlosEpia** [comment]
The default scenario is 2015. Using the code below, demand for each of the nuts3 zones is created every 15 minutes.
df_CTS = temporal.disagg_temporal_power_CTS(detailed=False, use_nuts3code=True)
df_hh = temporal.disagg_temporal_power_housholds_slp(by= "population")
df_ind = temporal.disagg_temporal_industry(source = "power")

Total demand CTS= 154.6 TWh
Total demand hh= 132.0 TWh
Total demand industry= 239.7 TWh

**Comment by CarlosEpia** [comment]
The demand per sector the first days of 2015 looks like this:
![demand_per_sector_2015](https://github.com/openego/powerd-data/assets/62600091/89ec1a4b-0eb6-464e-86c2-3a8123d1f7b8)

**Comment by CarlosEpia** [comment]
The total demand for the first days if 2015 looks like this:
![total_demand_2015](https://github.com/openego/powerd-data/assets/62600091/09659ea7-33e5-466f-bea1-2cd3d18e4447)

According to [IEA](https://www.iea.org/data-and-statistics/data-tools/real-time-electricity-tracker?tracker=true&from=2015-1-1&to=2015-1-1&category=demand&country=DEU) the demand on a weekday that week was:
![image](https://github.com/openego/powerd-data/assets/62600091/cacb292f-198b-4775-a29b-d1d57ab87993)

**Comment by CarlosEpia** [comment]
The peaks are significantly different 88 GW vs 54 GW. On the other hand, the lowest consumptions are similar: 34 GW vs 38 GW.

**Comment by CarlosEpia** [comment]
Demand Regio allows the generation of demand data till 2035. For that year, it is possible to generate CTS (136.8 TWh) and Industrial demand (247.6 TWh). There is a problem when executing
**temporal.disagg_temporal_power_housholds_slp(by= "population")**

  File "/tmp/ipykernel_5537/1952142773.py", line 1, in <cell line: 1>
    df_hh = temporal.disagg_temporal_power_housholds_slp(by= "population")

  File "/home/carlos/powerd-data-exc-new-air/demandregio-disaggregator/disaggregator/disaggregator/temporal.py", line 545, in disagg_temporal_power_housholds_slp
    sv_yearly = ((disagg_households_power(by=by,

  File "/home/carlos/powerd-data-exc-new-air/demandregio-disaggregator/disaggregator/disaggregator/spatial.py", line 66, in disagg_households_power
    power_nuts0 = elc_consumption_HH(year=year) / 1e3

  File "/home/carlos/powerd-data-exc-new-air/demandregio-disaggregator/disaggregator/disaggregator/data.py", line 85, in elc_consumption_HH
    df = float(database_get('spatial', table_id=cfg[key]['table_id'],

  File "/home/carlos/powerd-data-exc-new-air/demandregio-disaggregator/disaggregator/disaggregator/data.py", line 1998, in database_get
    return database_raw(query, force_update=force_update)

  File "/home/carlos/powerd-data-exc-new-air/demandregio-disaggregator/disaggregator/disaggregator/config.py", line 109, in database_raw
    raise ValueError('The returned pd.DataFrame is empty!')

ValueError: The returned pd.DataFrame is empty!

**Comment by CarlosEpia** [comment]
When using the alternative 
**temporal.disagg_temporal_power_housholds_slp(by= "households")**

  File "/tmp/ipykernel_5537/61527220.py", line 1, in <cell line: 1>
    df_hh = temporal.disagg_temporal_power_housholds_slp(by= "households")

  File "/home/carlos/powerd-data-exc-new-air/demandregio-disaggregator/disaggregator/disaggregator/temporal.py", line 545, in disagg_temporal_power_housholds_slp
    sv_yearly = ((disagg_households_power(by=by,

  File "/home/carlos/env/powerD/lib/python3.8/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)

AttributeError: 'DataFrame' object has no attribute 'to_frame'
