### ISSUE TITLE
Hi Installed Capacity per Production Type for central_lignite_CHP; central_coal_CHP

### ISSUE THREAD

**Issue by IsGut** [openego/powerd-data#142]
Considering generators containing "central" in em production type leading to hi values. In the figure afterwards, etrago and entso-e values are depicted.

Can you please let me know, how i can come close to entsoe/ energy-cahrt values? Best regards.

**Comment by IsGut** [comment]
![gen_hi_de](https://github.com/openego/powerd-data/assets/15251685/8a8b2585-af0b-4fd8-be08-d3acdad1e557)

**Comment by ClaraBuettner** [comment]
In the related issue #138 I already mentioned one idea for the problem. 
It looks like there is a conversion missing, and the installed CHP capacities for lignite and coal are given in kW. 
I will try to have a closer look. But would that be in line with the data from entsoe and energy charts?

**Comment by IsGut** [comment]
Yes on a first check.
