### ISSUE TITLE
Deleted data from sandbox zenodo

### ISSUE THREAD

**Issue by CarlosEpia** [openego/powerd-data#159]
All the data stored in Sandbox Zenodo was deleted and have to be  uploaded somewhere else and the links related must be updated. It can be found below the tasks that depend on data that is not anymore available:

- [x] data_bundle.download
- [x] scenario_parameters.download-pypsa-technology-data
- [ ] mastr.download-mastr-data

**Comment by iuljan** [comment]
@ClaraBuettner MaStR and pypsa download hasn't been fixed by #162, has it?
It's still the sandbox [URL](https://github.com/openego/powerd-data/blob/5e53698a715ae6391c54b65160840a2dbf75fd79/src/egon/data/datasets/mastr.py#L42) with deposit-IDs for new **1132987** and old: **808086** 
@nesnoj will this be fixed by you, updating the MaStR dump? 



For pypsa-technology data the URL goes to Zenodo but the deposit-id **5544025** also doesn't exist any more.
Could you upload this if you have the data available or shall I try to find the data?

**Comment by nesnoj** [comment]
> @nesnoj will this be fixed by you, updating the MaStR dump?

Yes, I'll re-upload mastr this week.

> For pypsa-technology data the URL goes to Zenodo but the deposit-id **5544025** also doesn't exist any more. Could you upload this if you have the data available or shall I try to find the data?

If I'm not mistaken, @ClaraBuettner was up to do this.

**Comment by ClaraBuettner** [comment]
> > For pypsa-technology data the URL goes to Zenodo but the deposit-id **5544025** also doesn't exist any more. Could you upload this if you have the data available or shall I try to find the data?
> 
> If I'm not mistaken, @ClaraBuettner was up to do this.

To be honest, I didn't know that this dataset also creates problems since it is not on the list above. But it looks like that data is already on zenodo, so we just need to update the download.

**Comment by nesnoj** [comment]
> > > For pypsa-technology data the URL goes to Zenodo but the deposit-id **5544025** also doesn't exist any more. Could you upload this if you have the data available or shall I try to find the data?
> > 
> > 
> > If I'm not mistaken, @ClaraBuettner was up to do this.
> 
> To be honest, I didn't know that this dataset also creates problems since it is not on the list above. But it looks like that data is already on zenodo, so we just need to update the download.

I'm updating the data-bundle in egon-data in https://github.com/openego/eGon-data/pull/1155
in egon-data the pypsa tech data was downloaded successfully in my today's run. And it's the same code for powerd so everything's fine.

**Comment by iuljan** [comment]
> in egon-data the pypsa tech data was downloaded successfully in my today's run. And it's the same code for powerd so everything's fine.

Sorry my bad. I just took the deposit id and used the search function of zenodo, which apparently doesn't work. @ClaraBuettner No need to do anything here.
