### ISSUE TITLE
CRS EPSG:4623 for ERA5 weather data?

### ISSUE THREAD

**Issue by nesnoj** [openego/powerd-data#179]
@ClaraBuettner Is there a specific reason why [EPSG:4623](https://epsg.io/4623) (French Guiana) is used [in the ERA5 task](https://github.com/openego/powerd-data/blob/5e53698a715ae6391c54b65160840a2dbf75fd79/src/egon/data/datasets/era5.py#L84) (added by you in eGon-data)?
I guess it's just a typo and you intended 4326 (WGS84) ?

**Comment by ClaraBuettner** [comment]
I think there is no reason and it is just a typo.
I'm wondering why that never created any problems...

**Comment by nesnoj** [comment]
Really odd, while the bounding box is restricted to that area, pyproj seems to return the same coords as WGS84 :thinking: . 
I'll fix this in eGon-data and here...
