### ISSUE TITLE
Inconsistecies last run status2019 (05-02-24)

### ISSUE THREAD

**Issue by CarlosEpia** [openego/powerd-data#209]
The next problems should be fixed in the next run of the scenario status2019:
- [x] Demands assigned to unexisting buses
- [x] There are no generators with carrier reservoir, solar_rooftop and run_of_river.
- [x] Total installed capacity should be around 210 GW in DE. It is currently way lower
- [x] There are 4 AC buses without country data. All of them located on the sea.

**Comment by CarlosEpia** [comment]
The distribution of installed capacities per carrier looks close to the expected values from [energy-charts](https://energy-charts.info/charts/installed_power/chart.htm?l=de&c=DE&year=2019&stacking=stacked_absolute). The total difference is about 10GW and it is mostly due to biomass generators.
![image](https://github.com/openego/powerd-data/assets/62600091/60f11c8f-7f87-40b3-98a4-4710d8a73c6f)
@IsGut OCGT generators are modelled as links.

**Comment by CarlosEpia** [comment]
The difference regarding biomass generators will be fixed in #213

**Comment by IsGut** [comment]
Hi @CarlosEpia , about the generation:

I am not sure anymore: how to handle hydro pumped storage? I fetched it from etrago.network.storage_units but it seems like there is data only for germany? 

Furthermore for germany, I have gaps for 

Hydro Pumped Storage    coal                   oil        
etrago            3149.0         32711.069        8024.027
entsoe            9422.0         25293.000        4356.000

I just see i have the _heat suffix included, eg central_coal_CHP_heat. You don't have it in your table. Do i have to drop all _heat columns?

Following plots. Data as .csv I could provide on request.


![nettostromerzeugung overall](https://github.com/openego/powerd-data/assets/15251685/e6e963c6-8532-4a20-a98d-41e64d779073)




![nettostromerzeugung_at](https://github.com/openego/powerd-data/assets/15251685/50e44ad0-7e43-468f-9889-100f64981a85)
![nettostromerzeugung_be](https://github.com/openego/powerd-data/assets/15251685/8f07066c-5ce8-4641-b795-1afd5de65d9b)
![nettostromerzeugung_ch](https://github.com/openego/powerd-data/assets/15251685/ed9d6f82-db41-4c79-bf6a-e85d0adcd023)
![nettostromerzeugung_cz](https://github.com/openego/powerd-data/assets/15251685/08160c8d-e05c-49e4-8b1f-195071a24f8d)
![nettostromerzeugung_de](https://github.com/openego/powerd-data/assets/15251685/f47666db-2ffd-4828-9b3c-81d49470feca)
![nettostromerzeugung_dk](https://github.com/openego/powerd-data/assets/15251685/65415b13-ea31-45b7-a020-04b396bd2a55)
![nettostromerzeugung_fr](https://github.com/openego/powerd-data/assets/15251685/563611f3-1b06-41d7-b022-102c039d947c)
![nettostromerzeugung_gb](https://github.com/openego/powerd-data/assets/15251685/9b5ff1a5-c7a7-43ab-9628-6d64e175b9aa)
![nettostromerzeugung_lu](https://github.com/openego/powerd-data/assets/15251685/8c26e1ee-9789-486a-809e-4d967f5f2780)
![nettostromerzeugung_nl](https://github.com/openego/powerd-data/assets/15251685/6e643a04-0815-4153-b470-1752506445d0)
![nettostromerzeugung_no](https://github.com/openego/powerd-data/assets/15251685/29d2c3a7-f7e1-43da-8c06-a75f2cc337bc)
![nettostromerzeugung_pl](https://github.com/openego/powerd-data/assets/15251685/fea67529-59ae-49d2-8b4d-212280373980)
![nettostromerzeugung_se](https://github.com/openego/powerd-data/assets/15251685/bb65856d-55a4-41b1-8e2b-95e8aed5fda1)

**Comment by IsGut** [comment]
@CarlosEpia , questions would be:

- how to handle hydro pumped storage
- can you have a look at nettostromerzeugung_de representing germany?
- I just see i have the _heat suffix included, eg central_coal_CHP_heat. You don't have it in your table. Do i have to drop all _heat columns?

Thanks in advance

**Comment by IsGut** [comment]
Hi @CarlosEpia . following the loads for germany comparing the etrago model and entsoe:

 
![DE_month_1_January](https://github.com/openego/powerd-data/assets/15251685/d598a196-7f3e-4eaa-bfd5-c91c85624396)
![DE_month_2_February](https://github.com/openego/powerd-data/assets/15251685/6a17b6df-9f7a-4df7-b9c8-e45321a8cc74)
![DE_month_3_March](https://github.com/openego/powerd-data/assets/15251685/1675f7bf-aff1-4376-b416-c7fe44b8ad8d)
![DE_month_4_April](https://github.com/openego/powerd-data/assets/15251685/53eaf150-2d0a-4db0-97f5-4b15787ac025)
![DE_month_5_May](https://github.com/openego/powerd-data/assets/15251685/ac41d87a-de2b-4a97-8eed-34bba0ea4669)
![DE_month_6_June](https://github.com/openego/powerd-data/assets/15251685/365d77f6-9222-454d-872f-2d06666b2e22)
![DE_month_7_July](https://github.com/openego/powerd-data/assets/15251685/5424698b-3cc8-430e-bc78-a731aeedd644)
![DE_month_8_August](https://github.com/openego/powerd-data/assets/15251685/cd09ffb5-6a54-4bb4-908d-936bff6e3d9d)
![DE_month_9_September](https://github.com/openego/powerd-data/assets/15251685/bf374c46-fe35-4d92-80ca-f73c3b1b11b5)
![DE_month_10_Oktober](https://github.com/openego/powerd-data/assets/15251685/46179cdb-c913-4ddb-878d-ded74e3a64d3)
![DE_month_11_November](https://github.com/openego/powerd-data/assets/15251685/98b6335a-3f7a-460f-8ac7-97359c6e9491)
![DE_month_12_Dezember](https://github.com/openego/powerd-data/assets/15251685/7d10fcb8-2671-497b-a172-ea85502cf34a)
![loads in germany whole year](https://github.com/openego/powerd-data/assets/15251685/2d566354-a41a-41ac-afd6-ccd749da0206)


is the difference okay?

**Comment by CarlosEpia** [comment]
> @CarlosEpia , questions would be:
> 
> * how to handle hydro pumped storage
> * can you have a look at nettostromerzeugung_de representing germany?
> * I just see i have the _heat suffix included, eg central_coal_CHP_heat. You don't have it in your table. Do i have to drop all _heat columns?
> 
> Thanks in advance

Hi Robert. About the hydro_pump_storage, there is room for improvement there. As you mentioned there are only capacities for Germany and the sum-up is smaller than expected. Issue #219 

Regarding the total installed capacity for Germany, apart from the biomass generators, the generators match carrier by carrier (keeping in mind some tolerance) the values provided by energy-charts.

The generators with the "_heat" suffix are the ones supposed to generate energy in the way of heat. What I do normally is filter all the buses with carrier "AC" in Germany and keep only generators connected to them.

**Comment by IsGut** [comment]
Hi Thorben, fyi @pl0via

**Comment by pl0via** [comment]
Hi Carlos,
as discussed: the substation emden-borssum (bus_id 29177) is stored in the static network model as 380-220 kv. (source: https://www.jao.eu/static-grid-model)

I have also attached the excel file for quick comparisons of the capacities and loads.

[eTraGo Validierung_update_02_16.xlsx](https://github.com/openego/powerd-data/files/14374785/eTraGo.Validierung_update_02_16.xlsx)

**Comment by pl0via** [comment]
Hi Carlos,

this is the evaluation in the form of a generation mix after carrying out the LOPF for the last database update (26.03.2024). As already mentioned in the last meeting, the largest deviation in generation occurs in France, where significantly more nuclear power is produced in eTraGo, most likely due to the partially high load values in Germany:

![AT_total](https://github.com/openego/powerd-data/assets/151061572/3c5afb56-39b1-4969-bb88-8092ea4cf4ad)
![BE_total](https://github.com/openego/powerd-data/assets/151061572/560287a5-8e34-438e-846a-e65a923e1d62)
![CH_total](https://github.com/openego/powerd-data/assets/151061572/57331b4a-64d4-4140-b26e-ed7bf386848b)
![CZ_total](https://github.com/openego/powerd-data/assets/151061572/43f0f666-529c-4635-abe5-4977e1fcd60a)
![DE_total](https://github.com/openego/powerd-data/assets/151061572/ac7f0ddd-e8ff-43f1-8b10-cea15478faef)
![DK_total](https://github.com/openego/powerd-data/assets/151061572/918075bf-8fbd-48ca-9ca3-0cdce9023fb4)
![FR_total](https://github.com/openego/powerd-data/assets/151061572/16b8cebf-7145-45a6-916d-d0fd04c15782)
![LU_total](https://github.com/openego/powerd-data/assets/151061572/4dbc3010-acbd-4369-8071-5195e916e754)
![NL_total](https://github.com/openego/powerd-data/assets/151061572/29f08d43-ec63-4904-95ed-0b5a271451e5)
![NO_total](https://github.com/openego/powerd-data/assets/151061572/62bfc181-0f5e-46ea-9d2f-18f83a9972df)
![PL_total](https://github.com/openego/powerd-data/assets/151061572/52b7cd6d-b460-4343-8db2-57a1ffdb625b)
![SE_total](https://github.com/openego/powerd-data/assets/151061572/c6f78034-9753-4756-a280-5bc9a27e2f97)
![Total Generation - All countries](https://github.com/openego/powerd-data/assets/151061572/d14a3498-78d0-4da1-937b-d9fe4c10b804)

**Comment by CarlosEpia** [comment]
Since the inconsistencies described at the beginning of this issue were already addressed and now we are analysing another version of the scenario2019, I proceed to close this issue. @pl0via Could you please replicate the same analysis you presented in your last comment using the latest available version and publish it on #231 ??
