### ISSUE TITLE
Finish eGon100RE

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/powerd-data#214]
To solve this issue, the next PR should be merged in the given order:
1. https://github.com/openego/powerd-data/pull/276
2. https://github.com/openego/powerd-data/pull/260
3. https://github.com/openego/powerd-data/pull/277
4. https://github.com/openego/powerd-data/pull/282
5. https://github.com/openego/powerd-data/pull/283
6. https://github.com/openego/powerd-data/pull/278
7. https://github.com/openego/powerd-data/pull/279
8. https://github.com/openego/powerd-data/pull/286
9. https://github.com/openego/powerd-data/pull/284
10. https://github.com/openego/powerd-data/pull/289
11. https://github.com/openego/powerd-data/pull/294
12. https://github.com/openego/powerd-data/pull/275
13. https://github.com/openego/powerd-data/pull/122
14. 

Open issues from eGon-data: 

- https://github.com/openego/eGon-data/issues/983 -> see #389 
- https://github.com/openego/eGon-data/issues/713 -> heat supply is distributed now
- https://github.com/openego/eGon-data/issues/580 -> already solved in run-status2019-and-egon100 branch
- https://github.com/openego/eGon-data/issues/698 -> this problem is not there anymore
- https://github.com/openego/eGon-data/issues/626 -> many things have changed in pypsa-eur and powerd-data, final check of loads still pending
-  https://github.com/openego/powerd-data/issues/239
- https://github.com/openego/powerd-data/issues/240
- https://github.com/openego/powerd-data/issues/274
- https://github.com/openego/powerd-data/issues/273
- https://github.com/openego/powerd-data/issues/271
- https://github.com/openego/powerd-data/issues/268
- https://github.com/openego/powerd-data/issues/267
- https://github.com/openego/powerd-data/issues/265
- https://github.com/openego/powerd-data/issues/264
- https://github.com/openego/powerd-data/issues/256
- https://github.com/openego/powerd-data/issues/255
- https://github.com/openego/powerd-data/issues/254
- https://github.com/openego/powerd-data/issues/252
- https://github.com/openego/powerd-data/issues/274
https://github.com/openego/powerd-data/issues/245
https://github.com/openego/powerd-data/issues/244
https://github.com/openego/powerd-data/issues/243
https://github.com/openego/powerd-data/issues/241
https://github.com/openego/powerd-data/issues/240
https://github.com/openego/powerd-data/issues/237
https://github.com/openego/powerd-data/issues/232

**Comment by CarlosEpia** [comment]
The scenario eGon100RE was already finished. The validation process is taking place in #280. This Issue can be closed.
