### ISSUE TITLE
Wrong pumped_hydro generators installed capacities

### ISSUE THREAD

**Issue by CarlosEpia** [openego/powerd-data#219]
There are only pumped_hydro generators for Germany and the sum-up is smaller than expected in the scenario2019.

**Comment by khelfen** [comment]
Hey @CarlosEpia :) We can confirm your findings for status2023. We have pumped hydro capacity of 3.3 GW in our model, but it should be [9.5 GW in Germany](https://www.energy-charts.info/charts/installed_power/chart.htm?l=de&c=DE&year=2023&legendItems=111011111111).

Besides your existing fix, we found that [here](https://github.com/openego/powerd-data/blob/befe77306d147c89173e12b4412407e23527a5ea/src/egon/data/datasets/storages/pumped_hydro.py#L147-L150) pumped hydro outside Germany is dropped. It should be checked if these pumped hydro plants are connected to the German grid. If so they should not be dropped for the `"Everything"` run.

**Comment by iuljan** [comment]
> Besides your existing fix, we found that [here](https://github.com/openego/powerd-data/blob/befe77306d147c89173e12b4412407e23527a5ea/src/egon/data/datasets/storages/pumped_hydro.py#L147-L150) pumped hydro outside Germany is dropped. It should be checked if these pumped hydro plants are connected to the German grid. If so they should not be dropped for the `"Everything"` run.

![image](https://github.com/openego/powerd-data/assets/51374526/4d409a56-fb92-4bab-b2a0-797f3dcd765d)

These are the ones, which are dropped (1.7 GW). As they are quite far away from the german border, we assume its fine.

**Comment by CarlosEpia** [comment]
Hi @khelfen and @nailend,  I was just dealing with these storages. I will include them as part of Germany since they are operated by a German network operator as part of their system. You can see some details [here](https://www.marktstammdatenregister.de/MaStR/Einheit/Detail/IndexOeffentlich/2256244)

**Comment by iuljan** [comment]
Around 1.8 GW of pumped-hydro capacity is missing (https://www.marktstammdatenregister.de/MaStR/Akteur/Marktakteur/DetailOeffentlich/2679571#zugehoerigeEinheiten).
This is due, to missing data in the openMastR dump from 2001, which is used for pumped hydro. The pp were registered only in january 2021 in MastR. Although the mastr dump used for hydro-power is from may 2021, the data was still missing.

To fix this, we propose to use the newest dump from january 2024 (https://zenodo.org/records/8225106) or at least the one from 2022 (this is simply done by switching to the `mastr_new_working_dir`. Probably this [commit](e460c128bb96a05aa83553665e508ec3a07b5a30) is also needed to avoid a conversion error of plz)

**Comment by CarlosEpia** [comment]
I would be in favour of using a newer dump from 2024 if it does not require too many changes. Maybe we could check if there are new column names or significant changes (like the last time we changed the MastR dump) and probably just replace cleanly the data that we used when we refer to mastr_new_working_dir.

**Comment by iuljan** [comment]
> I would be in favour of using a newer dump from 2024 if it does not require too many changes. Maybe we could check if there are new column names or significant changes (like the last time we changed the MastR dump) and probably just replace cleanly the data that we used when we refer to mastr_new_working_dir.

The zenodo record I linked, is already cleaned and formated by @nesnoj. I already implemented it for hydro power storage in  status2023. We will give feedback as soon as we have checked the results.

**Comment by nesnoj** [comment]
> The zenodo record I linked, is already cleaned and formated by @nesnoj. I already implemented it for hydro power storage in status2023. We will give feedback as soon as we have checked the results.

No, the one you linked is the general open-mastr release record, the correct ones with special eGon-data are:
- MaStR power unit registry for powerd-data: https://zenodo.org/records/10491882 (latest as used in powerd, 2024-01-08), referred to in *WORKING_DIR_MASTR_NEW*
- MaStR power unit registry for eGon-data: https://zenodo.org/records/10480958 (as used in eGon-data, 2022-11-17)
- MaStR power unit registry for eGon-data (legacy): https://zenodo.org/records/10480930 (as used in eGon-data and powerd, 2021-04-30), referred to in *WORKING_DIR_MASTR_OLD*

**Comment by iuljan** [comment]
> No, the one you linked is the general open-mastr release record, the correct ones with special eGon-data are:
> 
> * MaStR power unit registry for powerd-data: https://zenodo.org/records/10491882 (latest as used in powerd, 2024-01-08), referred to in _WORKING_DIR_MASTR_NEW_

ups, thanks for clarifying! 

@CarlosEpia I wrote a new [pumped_hydro function](https://github.com/openego/powerd-data/commit/6985efbebd824c6c92d2a0e0cf8c24a967b8d260), only using the MaStR-data and assigning capacities outside germany to the closes foreign buses at their voltage-level. This results in a total of 9.7 GW.  There is no differentiation for SH or whole germany though. And no filter for commissioning.

**Comment by CarlosEpia** [comment]
Hi @nailend I tried to use the mentioned new function and it works quite well also using the mastr from 2022.
Are you planning to use your model in eTraGo? If that is the case, assigning the foreign pumped hydro generators to their foreign closest bus can be problematic. During the execution of the clustering process, eTraGo clusters all the buses that belong to the same foreign country (except the UK and Denmark). It is made under the assumption that only one bus has elements as loads, generators, etc.

Could it be an option for you to limit the possible foreign buses to connect the pumped hydro generators to the buses returned by this [function](https://github.com/openego/powerd-data/blob/bad9f704bce388abaf0701401c17724d182717e4/src/egon/data/datasets/electrical_neighbours.py#L1454C5-L1475)?

**Comment by iuljan** [comment]
@CarlosEpia thx for the hint. As we will not apply any spatial clustering this shouldn't be a problem for us but definitely worth mentioning in the docstring.
@khelfen fyi

**Comment by khelfen** [comment]
> Hi @nailend I tried to use the mentioned new function and it works quite well also using the mastr from 2022. Are you planning to use your model in eTraGo? If that is the case, assigning the foreign pumped hydro generators to their foreign closest bus can be problematic. During the execution of the clustering process, eTraGo clusters all the buses that belong to the same foreign country (except the UK and Denmark). It is made under the assumption that only one bus has elements as loads, generators, etc.
> 
> Could it be an option for you to limit the possible foreign buses to connect the pumped hydro generators to the buses returned by this [function](https://github.com/openego/powerd-data/blob/bad9f704bce388abaf0701401c17724d182717e4/src/egon/data/datasets/electrical_neighbours.py#L754-L803)?

In this case I would suggest that eTraGo should aggregate all loads and generators within a country and assign them to a bus before running the cluster algorithm. Or am I missing something important why this is not done in eTraGo?

For our project we do not plan to use spatial clustering and it should have no effect.

**Comment by CarlosEpia** [comment]
> > Hi @nailend I tried to use the mentioned new function and it works quite well also using the mastr from 2022. Are you planning to use your model in eTraGo? If that is the case, assigning the foreign pumped hydro generators to their foreign closest bus can be problematic. During the execution of the clustering process, eTraGo clusters all the buses that belong to the same foreign country (except the UK and Denmark). It is made under the assumption that only one bus has elements as loads, generators, etc.
> > Could it be an option for you to limit the possible foreign buses to connect the pumped hydro generators to the buses returned by this [function](https://github.com/openego/powerd-data/blob/bad9f704bce388abaf0701401c17724d182717e4/src/egon/data/datasets/electrical_neighbours.py#L754-L803)?
> 
> In this case I would suggest that eTraGo should aggregate all loads and generators within a country and assign them to a bus before running the cluster algorithm. Or am I missing something important why this is not done in eTraGo?
> 
> For our project we do not plan to use spatial clustering and it should have no effect.

@khelfen Since you are not going to use spatial clustering in eTrago I think it is fine for you to leave it like it is now. In our case, I will implement that small change, considering that we plan to use that function and eTraGo decides how many and which buses to keep per foreign country based on the condition of loads, generators or storage units attached to them. It is important for the case of the UK and Denmark. Additionally, all the data used from Entsoe allows only that level of spatial complexity.
