### ISSUE TITLE
Enhancement: Include Additional Storage Types (e.g., Battery Systems) from MaStR Data

### ISSUE THREAD

**Issue by khelfen** [openego/powerd-data#220]
## Description

Currently, the MaStR data on storages is only used for pumped hydro storage systems. This approach provides a solid foundation for hydro storage modeling but leaves out other significant storage types, such as battery storage systems. Home battery systems are distributed without using MaStR data but grid scale BESS are completely ignored.

## Suggested Enhancement

Use the MaStR data to include information on other types of energy storage systems, especially battery systems.

**Comment by CarlosEpia** [comment]
According to the 2022 mastr data, the total storage capacity is divided as described in this table:

Technologie Capacity[MW]
Batterie        4088.227603
Druckluft          0.207660
Pumpspeicher    9729.249235
Schwungrad         0.376400
Sonstige          31.683853

I think that it makes sense to adapt this [fuction](https://github.com/openego/powerd-data/blob/26623781c272428511b4e8712e8d21bcdf1c1584/src/egon/data/datasets/storages/__init__.py#L279-L503) to be able to process other carriers. Based on the shown capacities, I would limit it to pumped_hydro and BESS. I will assign this issue to myself. Does it make sense for you @khelfen and @nailend?

**Comment by khelfen** [comment]
Since the other capacities are super small, it's probably okay to prioritize BESS. Especially since BESS is growing fast it's becoming more and more relevant with each status update. In 2023 ([8.1 GW](https://www.energy-charts.info/charts/installed_power/chart.htm?l=de&c=DE&year=2023&legendItems=101011111111)) it's double what it was in 2022.
