### ISSUE TITLE
Incorrect Capacities for Gas Generators in status2023 Model

### ISSUE THREAD

**Issue by khelfen** [openego/powerd-data#229]
### Description

The capacities for "OCGT", "central_gas_CHP", and "industrial_gas_CHP" in the status2023 model are currently set to nearly 50 GW. However, according to the latest data available on [Energy Charts](https://www.energy-charts.info/charts/installed_power/chart.htm?l=de&c=DE&year=2023), these capacities should be approximately 36 GW. This discrepancy may lead to inaccurate modeling and analysis outcomes.

### Possible Relation to Previous Issues

This issue may be related to previous issue #221, which also addressed discrepancies in generator capacities. It's possible that the resolution of issue #221 did not fully correct the capacities for these specific gas generators.

### Suggested Actions

1. @CarlosEpia or @ClaraBuettner could you check if this is also the case for your status2019 model? Or let me know if I miss anything important and the capacity is actually correct? :D
2. Find why capacities are too high and resolve the issue :D

You can use this SQL snippet to check the capacities:
```
SELECT SUM(p_nom) FROM grid.egon_etrago_link
WHERE scn_name = 'status2019'
AND carrier IN ('central_gas_CHP', 'OCGT', 'industrial_gas_CHP')
AND (
	bus0 in (
		SELECT bus_id FROM grid.egon_etrago_bus
		WHERE country = 'DE'
		AND carrier = 'AC'
		AND scn_name = 'status2019'
	)
	OR bus1 in (
		SELECT bus_id FROM grid.egon_etrago_bus
		WHERE country = 'DE'
		AND carrier = 'AC'
		AND scn_name = 'status2019'
	)
)

```

**Comment by ClaraBuettner** [comment]
Did you take into account that the installed capacity for OCGTs is the thermal capacity?

**Comment by khelfen** [comment]
> Did you take into account that the installed capacity for OCGTs is the thermal capacity?

In this case, the capacity is only about 25 GW, which is too little :thinking: Have you checked this for the 2019 model? Furthermore, I used the filter `AND carrier = 'AC'`. Shouldn't "OCGT" be connected to none-"AC" buses in that case?

Also in eTraGo, when using `import_gen_from_links` "OCGT" plants are then connected to AC buses and therefore electric? Is this a bug in eTraGo?

**Comment by khelfen** [comment]
@ClaraBuettner My first guess is that the main problem (there may be more) is that in [`insert_chp_statusquo`](https://github.com/openego/powerd-data/blob/bad9f704bce388abaf0701401c17724d182717e4/src/egon/data/datasets/chp/__init__.py#L325) gas plants with a "ThermischeNutzleistung" of zero are dropped.

These plants should be part of the electric power plants, but are dropped in [`fill_etrago_generators`](https://github.com/openego/powerd-data/blob/54b981eff34ce807b7b11643ba2563f0307f8ecd/src/egon/data/datasets/fill_etrago_gen.py#L190-L195). Could you confirm this? And could you suggest a fix for this as I'm not firm in questions regarding gas? Should we remove the filter in `fill_etrago_generators` and include these gas generators in `grid.egon_etrago_generator`?

Also, I'm still wondering about my question from earlier:

> Shouldn't "OCGT" be connected to none-"AC" buses in that case?

**Comment by khelfen** [comment]
Okay, I finally understand it. It's because the [`efficiency`](https://github.com/openego/powerd-data/blob/bad9f704bce388abaf0701401c17724d182717e4/src/egon/data/datasets/power_etrago/match_ocgt.py#L70) has to be taken into account.

```
SELECT SUM(p_nom * efficiency) FROM grid.egon_etrago_link
WHERE scn_name = 'status2023'
AND carrier IN ('central_gas_CHP', 'OCGT', 'industrial_gas_CHP')
AND (
	bus0 in (
		SELECT bus_id FROM grid.egon_etrago_bus
		WHERE country = 'DE'
		AND carrier = 'AC'
		AND scn_name = 'status2023'
	)
	OR bus1 in (
		SELECT bus_id FROM grid.egon_etrago_bus
		WHERE country = 'DE'
		AND carrier = 'AC'
		AND scn_name = 'status2023'
	)
)
```

gives 35.1 GW, which is very close to the expected output. Therefore closing this Issue.
