### ISSUE TITLE
Include existing battery storages to the status2019 scenario

### ISSUE THREAD

**Issue by ulfmueller** [openego/powerd-data#23]
According to NEP there are 400 MW big batteries and 600 MW small home batteries in 2019 in Germany. I think the number is high enough to include it. Options I see:
- take the values from NEP and use the current method to regionalize it as if they were future plants and then have model the batteries in a flexible manner as we have done it before (**minimal solution**)

More sophisticated options:
- take the mastr data and use the regionalization on municipality level
- model the home batteries in a way that they minimize the flow to the grid from a new bus level called s.th. like 'low voltage' - there a part of the small PV and the demand would be connected to as well. In a rather easy eTraGo post processing approach we could try to define a reasonable ratio for the amount of demand and small PV would be connected to a certain low voltage bus with a certain battery capacity. For the self-consumption optimization there was the idea of either create a parallelized pre-optimization run for all of these small self-consumptions low voltage buses or try to integrate it e.g. limiting the flow to the bigger grid by e.g. the PV potential per hour ( p_nom * p_max_pu)

I think right now, we should implement only the minimal solution. Anyone wants to do it? @CarlosEpia @ClaraBuettner

**Comment by CarlosEpia** [comment]
Minimal solution implemented. solved in #65 and #38
