### ISSUE TITLE
path access error in windows using etrago.optimize()

### ISSUE THREAD

**Issue by pl0via** [openego/powerd-data#236]
After applying the latest changes in the "fixes/run-consecutive-method" branch, all clustering functions are now working. However, in etrago.optimize() there seems to be an incorrect transfer of the path in Windows, as shown in the screenshot. The file is available in the repository, but the access does not seem to work.

![no such file or directory](https://github.com/openego/powerd-data/assets/151061572/d6447790-5321-4bd2-8cdc-bb29136886d1)

**Comment by ClaraBuettner** [comment]
This seems to be related to https://github.com/openego/eTraGo/issues/726 .

**Comment by CarlosEpia** [comment]
Since this issue belongs to eTraGo, I proceed to close it. As @ClaraBuettner mentioned, it is already covered in this [issue](https://github.com/openego/eTraGo/issues/726).
