### ISSUE TITLE
`--scenarios` Parameter Causes Broken DAGs

### ISSUE THREAD

**Issue by khelfen** [openego/powerd-data#343]
#### Description
Using the CLI parameter `--scenarios` results in broken DAGs due to incorrect conversion of the parameter into `egon-data.configuration.yaml`. This causes the following error:

#### Error Message
```
Broken DAG: [.../eGon-data/SH1/code/src/egon/data/airflow/dags/pipeline.py]
Traceback (most recent call last):
  File "<string>", line 7, in __init__
  File ".../code/src/egon/data/datasets/__init__.py", line 277, in __post_init__
    last = list(self.tasks.last)[0]
IndexError: list index out of range
```

#### Cause
The parameter `--scenarios` is being incorrectly written into the YAML file as:
```yaml
--scenarios: '[''status2019'', ''eGon2035'']'
```

#### Expected Behavior
The parameter should be correctly translated into YAML as:
```yaml
--scenarios:
- status2019
- eGon2035
```

#### Steps to Reproduce
1. Use the CLI to run a scenario.
2. Observe the resulting YAML and notice the incorrect format.
3. Try to run the pipeline and observe the broken DAG error.

#### Impact
- The pipelines are unable to execute due to invalid configurations.
- Manual correction of the YAML file is required as a workaround.

#### Proposed Solution
Adjust the conversion logic to ensure the `--scenarios` parameter is written into the YAML file in the correct format.

**Comment by ClaraBuettner** [comment]
I have not started a new run for a couple of months, but I remember that we once had similar problems. 
@CarlosEpia: Do you know if that was fixed?

**Comment by CarlosEpia** [comment]
I think we faced that problem at some point. Since we always work with powerd-data by creating the egon-data.configuration.yaml in advance, the required changes were probably never done.

**Comment by khelfen** [comment]
The `click.option` was just missing the `multiple=True` parameter. It should now work as intended with the default value or over the cli with e.g. `egon-data --scenarios status2019 --scenarios eGon2035 serve`.
