### ISSUE TITLE
Insert e-mobility data for status2019 into tables

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/powerd-data#41]
Data on e-mobility is currently not inserted into the eTraGo tables for status2019. To do that, this script needs some adjustments because the scenario names are hard coded: https://github.com/openego/powerd-data/blob/dev/src/egon/data/datasets/emobility/motorized_individual_travel/__init__.py

It would be also better to use the cli parameter for scenario names.

**Comment by ulfmueller** [comment]
What I don't know right now, is if we need a new simbev data set which we can link to [here](https://github.com/openego/powerd-data/blob/98a8b9d451195ac27338692fccf130536f6d9538/src/egon/data/datasets/emobility/motorized_individual_travel/__init__.py#L272-L276) @ClaraBuettner do you have an idea?

**Comment by ulfmueller** [comment]
Besides the above mentioned, I hope the new code on [this branch](https://github.com/openego/powerd-data/tree/features/%2341-e-mobility-leftovers) should address the problem...
