### ISSUE TITLE
 industry.industrial-demand-distr fails in current run for entire Germany

### ISSUE THREAD

**Issue by ulfmueller** [openego/powerd-data#45]
the log:

> [2023-05-16 15:22:13,090] {taskinstance.py:901} INFO - Executing <Task(Industrial_demand_curves (versioned)): industry.industrial-demand-distr> on 2023-05-15T09:30:48.901072+00:00
> [2023-05-16 15:22:13,100] {standard_task_runner.py:54} INFO - Started process 21514 to run task
> [2023-05-16 15:22:13,161] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'powerd-status-quo-processing-pipeline', 'industry.industrial-demand-distr', '2023-05-15T09:30:48.901072+00:00', '--job_id', '192', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/dags/pipeline_status_quo.py', '--cfg_path', '/tmp/tmpdba4s5px']
> [2023-05-16 15:22:13,162] {standard_task_runner.py:78} INFO - Job 192: Subtask industry.industrial-demand-distr
> [2023-05-16 15:22:13,201] {logging_mixin.py:120} INFO - Running <TaskInstance: powerd-status-quo-processing-pipeline.industry.industrial-demand-distr 2023-05-15T09:30:48.901072+00:00 [running]> on host at36
> [2023-05-16 15:22:19,783] {logging_mixin.py:120} WARNING - /home/powerd/powerd-data/venv/lib/python3.8/site-packages/airflow/operators/python_operator.py:113: FutureWarning: The `op` parameter is deprecated and will be removed in a future release. Please use the `predicate` parameter instead.
>   return_value = self.execute_callable()
> [2023-05-16 15:23:55,318] {logging_mixin.py:120} WARNING - /home/powerd/powerd-data/venv/lib/python3.8/site-packages/airflow/operators/python_operator.py:113: FutureWarning: The `op` parameter is deprecated and will be removed in a future release. Please use the `predicate` parameter instead.
>   return_value = self.execute_callable()
> [2023-05-16 15:24:03,107] {logging_mixin.py:120} INFO - WARNING: No data returned by statement: 
>  SELECT nuts3, demand, wz FROM
>                 demand.
>                 egon_demandregio_cts_ind
>                 WHERE scenario = 'eGon2021'
>                 AND demand > 0
>                 AND wz IN
>                     (SELECT wz FROM demand.egon_demandregio_wz
>                          WHERE sector = 'industry')
> [2023-05-16 15:24:03,119] {taskinstance.py:1150} ERROR - 'demand'
> Traceback (most recent call last):
>   File "/home/powerd/powerd-data/venv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
>     return self._engine.get_loc(casted_key)
>   File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
>   File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
> KeyError: 'demand'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/powerd/powerd-data/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
>     result = task_copy.execute(context=context)
>   File "/home/powerd/powerd-data/powerd-data/src/egon/data/datasets/__init__.py", line 194, in skip_task
>     result = super(type(task), task).execute(*xs, **ks)
>   File "/home/powerd/powerd-data/venv/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 113, in execute
>     return_value = self.execute_callable()
>   File "/home/powerd/powerd-data/venv/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
>     return self.python_callable(*self.op_args, **self.op_kwargs)
>   File "/home/powerd/powerd-data/powerd-data/src/egon/data/datasets/industry/__init__.py", line 325, in industrial_demand_distr
>     demand_nuts3_b["demand"] * share_to_sites
>   File "/home/powerd/powerd-data/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 3458, in __getitem__
>     indexer = self.columns.get_loc(key)
>   File "/home/powerd/powerd-data/venv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
>     raise KeyError(key) from err
> KeyError: 'demand'
> [2023-05-16 15:24:03,170] {taskinstance.py:1187} INFO - Marking task as FAILED. dag_id=powerd-status-quo-processing-pipeline, task_id=industry.industrial-demand-distr, execution_date=20230515T093048, start_date=20230516T132213, end_date=20230516T132403
> [2023-05-16 15:24:03,265] {local_task_job.py:102} INFO - Task exited with return code 1

Anyone feels familiar with this code? @ClaraBuettner @CarlosEpia 
... if not, I can try to find out what goes wrong here...

**Comment by ClaraBuettner** [comment]
I think I know how to fix this and will implement a solution.

**Comment by ClaraBuettner** [comment]
I fixed this issue in #40
