### ISSUE TITLE
Adapt gas loads to sq historic

### ISSUE THREAD

**Issue by ulfmueller** [openego/powerd-data#5]
Two sources were evaluated: DemandRegio and Extremos. Extremos was selected, since it was used in egon-data, has data for H2, and data for further scenarios (till 2050). There is an extra workaround regarding the SQ scenario. There is no data in Extremos for 2019 but for 2020, therefore the data from 2020 will be scaled to match the total demand supplied in https://ag-energiebilanzen.de/wp-content/uploads/2020/10/ageb_20v_v1.pdf page 1.1
Total gas energy consumption from industry = 873.2 PJ -----> 242.55 TWh

**Comment by CarlosEpia** [comment]
It was decided with the team members that these loads are not going to be considered. This issue can be closed.
