### ISSUE TITLE
Model the neighboring countries in the historic sq

### ISSUE THREAD

**Issue by ulfmueller** [openego/powerd-data#8]
Different options to decide on: 

- [ ] take historic crossborder flows from entso-e
- [x] take historic ATC from entso-e and then one node per country including aggregates of different generators and the overall loads
- [ ] like the before but try to model fbmc

At first, probably stick to the current implementation of using p-e-s. Here we have to check:
- the status quo year (2019)
- split up input data task and p-e-s- execution (we don't need the latter one for the status2019 scenario). Could be handled by instead of executing `snakemake -j1` execute `snakemake -j1 prepare_sector_networks
`
- Update p-e-s to version 0.7.0 respectively p-e 0.7.0 and technology data 0.5.0 or even 'better' take the newest p-e 0.8.0 which incorporates p-e-s (the latter one is deprecated).
- Deal with our p-e-s fork. If we do the above two we could or have to get rid of the fork. We could first prepare_sector_networks then apply our changes within our workflow...

**Comment by ulfmueller** [comment]
I would stick to the secondly mentioned option and see the firstly mentioned option as a very nice-to-have

**Comment by ulfmueller** [comment]
concerning our status quo year 2019 maybe we can use this here: https://github.com/PyPSA/pypsa-eur/blob/master/config.default.yaml#L116

**Comment by ulfmueller** [comment]
As a minimal approach, I would leave the current status of p-e-s as it is in order to get the neighboring grid topology hence then based on a gridkit abstraction of 2018. In addition I created a [branch](https://github.com/openego/powerd-data/tree/features/%238-address-foreign-gen-capacities) in which I added two functions to get historic generation capacities and demand time series for the neighboring countries. 
@CarlosEpia if you like, as we talked about feel free to follow up on this by
a) creating mean values from the 15-min demand time values towards hourly values
b) executing the mentioned functions and write the data in our etrago tables for the scenario status2019

Thanks a lot!

**Comment by CarlosEpia** [comment]
Hi Ulf. Here is the list of carriers from entso-e and the proposed carriers for our scenario2019.
{
            'Biomass': "biomass",
            'Fossil Brown coal/Lignite': "lignite",
            'Fossil Coal-derived gas': "coal",
            'Fossil Gas': "CH4_NG",
            'Fossil Hard coal': "coal",
            'Fossil Oil': "oil",
            'Fossil Oil shale': "oil",
            'Fossil Peat': "biomass",
            'Geothermal': "geo_thermal",
            'Hydro Pumped Storage': "Hydro Pumped Storage",
            'Hydro Run-of-river and poundage': "run_of_river",
            'Hydro Water Reservoir': "reservoir",
            'Marine': "marine",
            'Nuclear': "nuclear",
            'Other': "others",
            'Other renewable': "others",
            'Solar': "solar",
            'Waste': "others",
            'Wind Offshore': "wind_offshore",
            'Wind Onshore': "wind_onshore",
        }
