### ISSUE TITLE
Duplicate foreign generators

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/powerd-data#86]
In the results of the Germany run, many (maybe all) generators of foreign countries are in there twice, one time with the correct bus_id, another time with a bus_id that does not exist. 

I don't know if that is a bug in the code or happened because a task was re-executed or sth. 
@CarlosEpia and @ulfmueller: I'm not very sure who did the implementation in the end, could the one who did it have a look?

**Comment by CarlosEpia** [comment]
I check the foreign generators in the new run and found that there are no repeated. The described problem was most likely due to re-executed tasks.
