### ISSUE TITLE
Check if a dependency from mit_charging_infrastructure to emobility_mit is useful

### ISSUE THREAD

**Issue by ulfmueller** [openego/powerd-data#95]
so far nothing depends on the mit_charging_infrastructure. This seems to be rather wrong. I would assume that at least the emobility_mit task is dependent on that. Since that task is starting so late in the process anyhow (due to other dependencies) so far this is no problem. But maybe in the light of any other more restructuring it would make sense to straighten this out...

**Comment by ClaraBuettner** [comment]
I had a look into the scripts from both datasets but couldn't find a dependency. 
I could imagine that the linkage is part of the runs from `tracbev` and `simbev`. Probably the dependency is not needed because these runs build up on each other.
